// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb7O7CdhZhB6Kz2h34Nn7dltob21uwT1I',
    appId: '1:869629193865:web:7841878c216c49a8d66058',
    messagingSenderId: '869629193865',
    projectId: 'jani-pastol',
    authDomain: 'jani-pastol.firebaseapp.com',
    storageBucket: 'jani-pastol.appspot.com',
    measurementId: 'G-QCPHGC5GZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vpy1eRpdDTAEqgd3Lg3TPz6mpKBroMs',
    appId: '1:869629193865:android:bd100953cdac83a1d66058',
    messagingSenderId: '869629193865',
    projectId: 'jani-pastol',
    storageBucket: 'jani-pastol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYHYIcNr9ArvGPNYdkgxBKr7JRcGsVko',
    appId: '1:869629193865:ios:f61f4d6543c7c863d66058',
    messagingSenderId: '869629193865',
    projectId: 'jani-pastol',
    storageBucket: 'jani-pastol.appspot.com',
    iosBundleId: 'com.example.jani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYHYIcNr9ArvGPNYdkgxBKr7JRcGsVko',
    appId: '1:869629193865:ios:79c62dddbdf13ae4d66058',
    messagingSenderId: '869629193865',
    projectId: 'jani-pastol',
    storageBucket: 'jani-pastol.appspot.com',
    iosBundleId: 'com.example.jani.RunnerTests',
  );
}
